import { Download, Heart, MapPin, Package, Settings, User } from 'lucide-react';
import { Seo } from '../../shared/ui/Seo.jsx';

const panels = [
  ['Profile', User, 'Manage identity, avatar, and secure credentials.'],
  ['Addresses', MapPin, 'Saved shipping destinations with default selection.'],
  ['Orders', Package, 'Track delivery status, payment status, and returns.'],
  ['Wishlist', Heart, 'Signals used by the recommendation engine.'],
  ['Invoices', Download, 'Download PDF invoices generated by PDFKit.'],
  ['Settings', Settings, 'Preferences, email, and session management.']
];

export default function DashboardPage() {
  return (
    <>
      <Seo title="Account | NOIRTHREAD" description="Manage your NOIRTHREAD profile, orders, wishlist, invoices, and preferences." path="/account" />
      <section className="noir-container py-12 lg:py-20">
        <h1 className="font-heading text-5xl font-bold">Account</h1>
        <div className="mt-8 grid gap-4 md:grid-cols-2 xl:grid-cols-3">
          {panels.map(([title, Icon, copy]) => (
            <article key={title} className="border border-noir-border bg-noir-surface p-6">
              <Icon />
              <h2 className="mt-8 font-heading text-2xl font-semibold">{title}</h2>
              <p className="mt-3 text-sm leading-6 text-noir-muted">{copy}</p>
            </article>
          ))}
        </div>
      </section>
    </>
  );
}
